development:
  database: posts_developpment
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  database: posts_production
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  database: posts_test
  adapter: postgresql
  username: postgres
  password: password
  host: localhost
  port: 5432
